server:
  port: 9004  # / 9004
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.5.94:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'