server:
  port: 3344
spring:
  application:
    name: cloud-config-center  # 注册进eureka Server 的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hualong-hu/springcloud-config.git # github 仓库位置
          ## 搜索目录
          search-paths:
            - springcloud-config
          # 读取的分支
          label: main
  # rabbitMq的相关配置
  rabbitmq:
    host: 150.158.5.94
    port: 5672
    username: guest
    password: guest

#  rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/