server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        配置nacos地址
        server-addr: 150.158.5.94:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
