server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.5.94:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true