server:
  port: 9527
spring:
  application:
    name: cloud-gateway
    ## GateWay配置
  ## GateWay配置
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
#            - Between=2020-11-27T14:55:21.985+08:00[Asia/Shanghai],2020-11-27T14:59:30.985+08:00[Asia/Shanghai]
#            - Before=2020-11-27T15:02:00.985+08:00[Asia/Shanghai]

        - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8002  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          # uri: lb://cloud-payment-service  解释：lb 属于GateWay 的关键字，代表是动态uri，
          #  即代表使用的是服务注册中心的微服务名，它默认开启使用负载均衡机制
          predicates:
            - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
            - After=2020-11-27T14:55:21.985+08:00[Asia/Shanghai]  #断言，在此时间之后进行路由
#            - Cookie=username,luosheng
#            - Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
